### ISSUE TITLE
RecommendItemsToItem API 2.0 error

### ISSUE THREAD

**Issue by gingerlime** [Recombee/ruby-api-client#6]
I was using `ItemBasedRecommendation` before and it was working fine. Looks like it's deprecated now? so I switched to `RecommendItemsToItem`... however I cannot get results from it, and keep getting this 400 error

```ruby
[101] pry(main)> client.send RecommendItemsToItem.new(id, "NULL", 20, :scenario => 'XYZ')
RecombeeApiClient::ResponseError: ResponseError: status: 400, description: {"error": "Error occured during processing the request: Invalid operand types for operator '+': number and null. Near line 1 position 259."}
from /usr/local/bundle/gems/recombee_api_client-3.2.0/lib/recombee_api_client.rb:102:in `check_errors'
```

I tried using `nil` instead of `"NULL"`, as well as passing a valid user id, but I get the same error always.

**Comment by OndraFiedler** [comment]
Can you please provide ID of the database that you are using?
It looks like an error in a ReQL filter/booster (maybe associated to the Scenario?).

**Comment by gingerlime** [comment]
Hi @OndraFiedler 👋 

Ah, thank you. It's strange, because the error didn't give me any clue. When I use the preview option for the scenario it works fine though? the database id is `fw7f6fc3-prod`

**Comment by OndraFiedler** [comment]
We have taken a look at your database, and the issue is not related to the Ruby SDK, but to the ReQL boosters applied to your Scenarios.

---

The issue with the Booster rule is quite tricky, as it appears only for certain items (due to using `context_item` in the rule).
E.g. for item `1848` it appears also in the Preview.

You use following Booster:
```python
if 'contents' == context_item["contents"] then 
  1.5
else
  1 + reduce("+", map(lambda 'x': if 'x' in context_item["contents"] then 0.3 else 0, 'contents'))
```

If the `map` on the 4th line yields an empty array, the `reduce` function has no values to sum, and returns `null`.
`1 + null` is not a valid operation.

You can prevent this by supplying an initial value (0) to the `reduce` function like this:

```python
  1 + reduce("+", map(lambda 'x': if 'x' in context_item["contents"] then 0.3 else 0, 'contents', 0))
```

Therefore `0` is returned instead of the `null` in case of the empty result from `map`, and `1 + 0` is a valid operation.

**Comment by gingerlime** [comment]
Thank you, @OndraFiedler. I wonder why I couldn't see this error when I previewed the scenarios.

A couple of suggestions if I may :)

1. let the error message point to the specific scenario by name, rather than just show an error message that is hard to associate
2. have some example in the docs about how to boost items that match some array properties. For example, let's say items can have a property `colors` (an array of colors), then boost those items that have more colors matching, not necessarily all of them...

**Comment by gingerlime** [comment]
p.s. I think the line should be 

```python
1 + reduce("+", map(lambda 'x': if 'x' in context_item["contents"] then 0.3 else 0, 'contents'), 0)
```

 right?

**Comment by OndraFiedler** [comment]
> p.s. I think the line should be
> right?

Yes, this is correct.
Sorry about the misplaced parenthesis.
